### ISSUE TITLE
H2 sql interporlation

### ISSUE THREAD

**Issue by meloniasty** [tpolecat/doobie#1049]
hi,
i'm using doobie 0.5.4 with mysql driver for real app and h2 for tests

I have problem that in tests sql interpolation does not work properly. 
for example 

```
def limitation(limit: Int = 0, offset: Int = 0): Fragment =
    if (limit <= 0) fr"" else if (offset <= 0) fr"""LIMIT ${limit}""" else  fr"""LIMIT ${limit} OFFSET ${offset}"""

def orderBy(sortColumn: String, sortOrder: String) = {
    fr"ORDER BY ${sortColumn} ${sortOrder}"
  }

val select = fr"select * from deals "

val sql = select ++ orderBy(column, order) ++ limitation(limit, offset)
```

for that query in H2 driver it does not work I'm getting error:

> org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement
> ORDER BY ? ? LIMIT ?  [42000-199]

but in Mysql driver it works fine

if I change method orderBy:
```
def orderBy(sortColumn: String, sortOrder: String) = {
    fr"ORDER BY" ++ Fragment.const(sortColumn) ++ fr" " ++ Fragment.const(sortOrder)
  }
```

it works also in H2

Is this behavior expected? Does H2 support full sql interpolation?

**Comment by jatcwang** [comment]
@meloniasty Doobie only constructs the SQL. It's up to the database engine to parse the decide whether the SQL and its parameters are valid. In this case it seems like H2 does not allow passing in the `ASC`/`DESC` part of the ORDER BY as a parameter

Since there are only two possible values (ASC/DESC), perhaps using Fragment.const is the better solution?

**Comment by Daenyth** [comment]
This is expected behavior
