### ISSUE TITLE
[Feature request] streaming API for PostgreSQL's COPY

### ISSUE THREAD

**Issue by Z1kkurat** [tpolecat/doobie#1056]
Currently Doobie supports PostgreSQL's COPY for any `F: Foldable` which severely limits its usage, since COPY is perfect for inserting large datasets, and large dataset, embedded in `Foldable` would probably overflow application memory.
It would be nice to have Doobie API that can work with `Stream[F, A]` or `Stream[ConnectionIO, A]` to load large amounts of data into Postgres tables.

**Comment by Z1kkurat** [comment]
Current JDBC API for this is [here](https://jdbc.postgresql.org/documentation/publicapi/org/postgresql/copy/CopyManager.html#copyIn-java.lang.String-java.io.InputStream-).
I guess our only choice is turning FS2's Stream into Java's InputStream by some means to be consumer by this API.

**Comment by tpolecat** [comment]
This is the method in question

https://github.com/tpolecat/doobie/blob/master/modules/postgres/src/main/scala/doobie/postgres/syntax/FragmentSyntax.scala#L16-L32

It needs to take a stream instead of a foldable, but it's unclear what the effect type of the stream needs to be. It may need to be `G[_]: ConcurrentEffect` or something like that, depending on what the Java iostream stuff requires.

**Comment by Daenyth** [comment]
It *seems* like this should be able to be implemented using `fs2.io.toInputStreamResource` which indeed requires `ConcurrentEffect`
