### ISSUE TITLE
LogHandler with Quill

### ISSUE THREAD

**Issue by TannerYoung** [tpolecat/doobie#1062]
It appears that queries using quill integration don't get logged by any implicit log handler. 

Is there a way to explicitly log them?

**Comment by zhenwenc** [comment]
This is caused by the Quill [query logger](https://github.com/getquill/quill/blob/master/quill-jdbc/src/main/scala/io/getquill/context/jdbc/JdbcContextBase.scala#L17) hasn't been invoked by the query execution methods in [DoobieContextBase](https://github.com/tpolecat/doobie/blob/master/modules/quill/src/main/scala/doobie/quill/DoobieContextBase.scala#L36-L46), see [default implementation](https://github.com/getquill/quill/blob/master/quill-jdbc/src/main/scala/io/getquill/context/jdbc/JdbcContextBase.scala#L37-L43) of `JdbcContextBase #executeQuery` for example.

For Reference: [Logging executed query at runtime (Quill)](https://getquill.io/#logging-runtime)
