### ISSUE TITLE
PSQLException: Can't infer the SQL type to use for an instance of java.time.Instant.

### ISSUE THREAD

**Issue by Fristi** [tpolecat/doobie#1095]
Since upgrading to 0.8.7 I get

```
Exception: org.postgresql.util.PSQLException: Can't infer the SQL type to use for an instance of java.time.Instant. Use setObject() with an explicit Types value to specify the type to use.
```

**Comment by mlopes** [comment]
I'm getting a similar one which I think might be related, also when upgrading from `0.8.6` to `0.8.7`.

`com.microsoft.sqlserver.jdbc.SQLServerException: The conversion to class java.time.Instant is unsupported.`

**Comment by zsambek** [comment]
@Fristi Since doobie is only a wrapper around the JDBC if the underlying JDBC does not support the given type then, unfortunately, we could not do anything. 

From Pg JDBC Driver docs:
> Note that ZonedDateTime, Instant and OffsetTime / TIME [ WITHOUT TIMEZONE ] are not supported.

`java.time.Instant` only worked previously because it was converted to `java.sql.Timestamp` before passing to the underlying JDBC library. 

What I can advise is to use a data type that is supported by the JDBC driver you are using or implement a custom mapping for `java.time.Instant`. You can learn more about Custom Mappings: [here](https://tpolecat.github.io/doobie/docs/12-Custom-Mappings.html).

**Comment by mlopes** [comment]
@zsambek thanks for the clarification, I guess the confusion came from the BC break on a patch version change.

**Comment by zsambek** [comment]
@mlopes We are providing instances, not for just `java.time.Instant`, but all other JSR-310 data types too. 
Providing instance means that we provide a Meta that knows to which methods should we call on the PreparedStatement and on the ResultSet to serialize and deserialize the type. 
The problem here is that the Pg JDBC does not support `java.time.Instant` serialization and deserialization. You can read more about JSR-310 types which are supported by PostgreSQL JDBC: [here](https://jdbc.postgresql.org/documentation/head/8-date-time.html)

`java.time.Instant` serialization only worked before because doobie did not use the recommended method to serialize and deserialize the type using `_.setObject(col, instant)` and `_.getObject(col, classOf[java.time.Instant])` instead it first converted it to a `java.sql.Timestamp` and serialized as a `java.sql.Timestamp`.

**Comment by tpolecat** [comment]
We may have been too hasty removing the old instances. You can add the instance back if it's working ok for you. `Meta[Timestamp].imap(...`, etc.

**Comment by zsambek** [comment]
@tpolecat 
Maybe we could provide a different java.time.Instant Meta in PG instances.

**Comment by zsambek** [comment]
@tpolecat Started to work on the revert for the `java.time.Instant`

**Comment by tpolecat** [comment]
Fixed in 0.8.8, see https://github.com/tpolecat/doobie/releases

**Comment by bjhartin** [comment]
@tpolecat This is occurring for us after upgrading an old app from 0.5.3 to 0.9.0:

- Added `import doobie.implicits.javatime._`.
- `IOChecker` tests work fine
- A test which doesn't use `check` but instead executes the `IO` to insert data fails with this exception.

Fixed by adding an implicit `Instant` meta which goes to/from `Timestamp`, but I don't think I should need this.

**Comment by jatcwang** [comment]
@bjhartin are you using postgres? In which case the import should be `import doobie.implicits.legacy.instant._` like in the release notes

**Comment by wwbakker** [comment]
For future reference, or if someone needs a working type mapping for `java.time.Instant` <--> `timestamptz`. The following seems to work for me:

```scala
package your.project

import doobie.util.meta.Meta
import doobie.util.meta.MetaConstructors

trait JavaInstantInstances extends MetaConstructors {

  import doobie.enumerated.JdbcType.*

  given Meta[java.time.Instant] =
    Basic.one[java.time.Instant](
      TimestampWithTimezone,
      Nil,
      (rs, idx) => Option(rs.getTimestamp(idx)).map(_.toInstant).orNull,
      (ps, idx, ist) => ps.setTimestamp(idx, Option(ist).map(java.sql.Timestamp.from).orNull),
      (ps, idx, ist) => ps.updateTimestamp(idx, Option(ist).map(java.sql.Timestamp.from).orNull)
    )
}

```
It's scala 3, but it probably should work for scala 2 too, if you replace the `.*` with `._` and `given` with `implicit val JavaTimeInstantMeta`

**Comment by jatcwang** [comment]
Yep that looks good. We have them as traits so people can build their own single import for all the base Meta instances for their project/DB 👍
