### ISSUE TITLE
Runtime Exception on mapping timestamp to Instant

### ISSUE THREAD

**Issue by dom-nguyen** [tpolecat/doobie#1125]
```
import doobie.implicits.javatime._

    case class Moo(id: Int, updated: Instant)
    val sql =
      sql"""
           SELECT id, updated
           FROM foo.moo
         """.query[Moo]
    check(sql) // Passes

    sql.option.transact(transactor).unsafeRunSync()
```

updated is a `timestamp` column

Got runtime exception

```
conversion to class java.time.Instant from timestamp not supported
org.postgresql.util.PSQLException: conversion to class java.time.Instant from timestamp not supported
	at org.postgresql.jdbc.PgResultSet.getObject(PgResultSet.java:3446)
	at doobie.util.meta.TimeMetaInstances.$anonfun$JavaTimeInstantMeta$1(timemeta.scala:23)
	at doobie.util.meta.TimeMetaInstances.$anonfun$JavaTimeInstantMeta$1$adapted(timemeta.scala:23)
```

**Comment by tpolecat** [comment]
You need `import doobie.implicits.legacy.instant._` here because the Postgres driver doesn't support `Instant` via JDBC 4.2's general support for JSR-310 types. I added a note to this effect in the [release notes](https://github.com/tpolecat/doobie/releases/tag/v0.8.8). Sorry for the confusion.

Give it a try and comment or close, pls.

**Comment by dom-nguyen** [comment]
Yeah the `legacy` one always worked. I just didn't think it was expected that the new implementation doesn't work with Postgres. Thanks for the clarification.
