### ISSUE TITLE
about doobie Parameterized Queries

### ISSUE THREAD

**Issue by peter-hst** [tpolecat/doobie#1439]
sql"select * from ${tableName}" can't support?

`
HttpRoutes.of[Task] {
 case GET -> Root / "test" / "list2" / IntVar(i) => {
      Ok(list[FndUdc]("fnd_udc", if (i == 1) true else false).unsafeRunSync().asJson)
    }

def list[B: Read](tableName: String, cond: Boolean) = {
    // val sqlStr = s"SELECT * from fnd_udc "
    val sql = sql"SELECT * FROM $tableName where is_deleted = $cond"

    //    val sql = fr"SELECT * from " ++  fr"${name}" ++ fr" where is_deleted = $cond"
    transactor.use(xa => sql.query[B].to[List].transact(xa))
  }

`

**Comment by jatcwang** [comment]
Every interpolation with `fr` turns it into a `?` in the actual SQL you send to the database.

So `fr"SELECT * FROM ${tableName}"` turns into `SELECT * FROM ?` which isn't a valid parameterized query in most (if not all) DBs.

What you want is `fr"SELECT * FROM " ++ Fragment.const(tableName)`

Please be very careful when using Fragment.const to make sure it's a value you control (and not coming from the user), otherwise you may introduce SQL injection vulnerabilities.

**Comment by peter-hst** [comment]
Thanks
