### ISSUE TITLE
Processing large result sets

### ISSUE THREAD

**Issue by miketkelly** [tpolecat/doobie#161]
First, thank you for making this library available. I think its quite ingenious, and I really like code I end up with when using it. One thing holding me back from testing it more broadly is performance on some of my common use cases. Maybe its early in doobie's lifetime for performance enhancements, but I though I'd toss this over in case there's an easy workaround (I didn't find one).

Very often I have queries that will return a few million rows back. Below are some benchmark results comparing JDBC, Slick, and Doobie, returning various numbers of rows back from a four column table (connection time is included). Doobie struggles on large result sets.

One bottleneck seems to be the match statement in resultset kleisliTrans: https://github.com/tpolecat/doobie/blob/master/core/src/main/scala/doobie/free/resultset.scala#L1583. On a four column table, its called nine times per row. Given that this work is redundant (the transformation is the same for each row), is there a way to avoid this?

```
[info] Benchmark                 (n)  Mode  Cnt   Score    Error  Units
[info] PerfTest.test_doobie       10  avgt    5   0.015 ±  0.001   s/op
[info] PerfTest.test_doobie     1000  avgt    5   0.061 ±  0.007   s/op
[info] PerfTest.test_doobie   100000  avgt    5   4.355 ±  0.355   s/op
[info] PerfTest.test_doobie  1000000  avgt    5  44.889 ±  3.233   s/op
[info] PerfTest.test_jdbc         10  avgt    5   0.012 ±  0.001   s/op
[info] PerfTest.test_jdbc       1000  avgt    5   0.015 ±  0.001   s/op
[info] PerfTest.test_jdbc     100000  avgt    5   0.278 ±  0.010   s/op
[info] PerfTest.test_jdbc    1000000  avgt    5   2.707 ±  0.371   s/op
[info] PerfTest.test_slick        10  avgt    5   0.015 ±  0.002   s/op
[info] PerfTest.test_slick      1000  avgt    5   0.019 ±  0.003   s/op
[info] PerfTest.test_slick    100000  avgt    5   0.286 ±  0.013   s/op
[info] PerfTest.test_slick   1000000  avgt    5   2.770 ±  0.210   s/op
```

Again, brilliant work!

**Comment by tpolecat** [comment]
Cool, thanks for this. As you suspected I have not done any performance work yet. Are you just doing `sql"..."query[Blah].list` or similar?

**Comment by miketkelly** [comment]
Yes,`sql"...".query[CaseClass].list.transact(xs).run`

**Comment by tpolecat** [comment]
Just off the top of my head:

- scalaz-stream's `runLog` accumulates by vector concatenation, and then this is converted to a list. If you use `.vector` instead of `.list` you might do a tiny bit better. You could also `.sink` to an effectful action that accumulates values in some other way.
- Every column read is followed by a `wasNull` check, which could be eliminated for non-nullable columns at the cost of some runtime safety, or combined in a single primitive operation (which would require deviating from the current design of the `.free` package). If the interpreter is in fact the bottleneck then "bigger" primitives at least for resultset-handling operations might end up being worthwhile.

**Comment by tpolecat** [comment]
Just messing around at lunch I found that I can speed things up a ton by moving the most commonly executed operations to the top of the `case` statement. Immediate 3x speedup in some simple tests. So that's worth chasing down. Hacking up a tagging system to turn the interpreter into a JVM case switch would be sucky codewise but would probably be a huge perf win. To be continued...

**Comment by miketkelly** [comment]
Hah! I was just typing that up. Just putting WasNull at the top is about a 25% improvement in my case. So a tagging system probably would solve it. Thanks for checking into it.

**Comment by tpolecat** [comment]
Also helps a bit to pre-construct the cases that have no parameters; and perhaps speculatively construct ops for indexed operations on small `n` like `getString(1)`. Looks like a lot of relatively easy wins.

**Comment by tpolecat** [comment]
The `~>` is also getting re-constructed for each operation even though it's only needed once per call to `transK` ... something needs to be stricter.

**Comment by tpolecat** [comment]
I looked at this some more last night and the immediate easy wins are:

- Invert the "expression problem" encoding by placing the default kleisli mapping on `ResultSetOp` and then we can use normal O(1) dispatch instead of `match`'s table scan.
- Change `Query` to use the `PreparedStatementIO` lifted stream (or even a custom unroller in `ResultSetIO`) to implement `.vector`.
- Either turn off the `wasNull` check or add it to the JDBC benchmark to make it fair. In practice I always want this check so I'm reluctant to remove it. Could be a system flag or something.

Longer term look into pushing `Atom` and `Composite` down into the `.free` layer. This would allow things like `get[(String, Int, Boolean)]` to be implemented as a single atomic effect instead of six (three `get`s and three `wasNull`s). This could also be done with a custom applicative that fuses native operations, which would be very cool if I can figure out how to do it.

**Comment by tpolecat** [comment]
Latest numbers, comparing raw jdbc with prototype doobie changes. They are indistinguishable for resultsets up to about 10^6 and a constant factor of about 2x accumulates up to about 10^5 rows where jdbc and doobie both seem to max out.

```
  jdbc               10       7.66 ms         1304.92 rows/s
  jdbc              100       8.55 ms        11701.00 rows/s
  jdbc             1000       9.53 ms       104958.61 rows/s
  jdbc            10000      24.01 ms       416567.30 rows/s
  jdbc           100000     141.13 ms       708582.20 rows/s
  jdbc          1000000    1391.21 ms       718800.49 rows/s

  proto              10       6.87 ms         1456.11 rows/s
  proto             100       9.05 ms        11050.56 rows/s
  proto            1000      14.32 ms        69845.99 rows/s
  proto           10000      24.92 ms       401214.87 rows/s
  proto          100000     203.97 ms       490262.67 rows/s
  proto         1000000    2766.53 ms       361463.78 rows/s // GC-related?
```

Prototype changes:
- inverting the expression problem as described above
- using a low-level `unroll` combinator instead of streams when fetching a collection
- redefining `Meta`, `Atom`, and `Composite` in terms of raw JDBC functions rather than monadic actions, which allows composite fetch/store without any `Free` overhead.

**Comment by unoexperto** [comment]
I'm on 0.6.0-M2 right now. Was this problem addressed ? It's still slow for me (~11X slower than getting data via custom [PGCOPY BINARY streaming parser](https://gitlab.com/unoexperto/scala-tricks/blob/master/src/main/scala/com/walkmind/scodec/pgcopy/PgCopyCodecs.scala) that I wrote). And I suspect issue is not doobie but fs2.
