### ISSUE TITLE
Question regarding transactions and rollbacks

### ISSUE THREAD

**Issue by kyri-petrou** [tpolecat/doobie#1725]
Hi there 👋 I'm trying to build something and I'm not sure what is the best way to implement this and thought to reach out for some guidance. Let's assume that we have this very simple program:

```scala
private def isTimeValid(t: ZonedDateTime): IO[Boolean] = IO(???) // Some call to some other service

def genNewTime(tx: Transactor[IO]): IO[ZonedDateTime] =
  for {
    newTime <- sql"UPDATE main_table SET new_time = NOW() WHERE id = 42".update
      .withUniqueGeneratedKeys[ZonedDateTime]("new_time")
      .transact(tx)
    isValid <- isTimeValid(newTime)
    _       <- IO.raiseUnless(isValid)(new Throwable("invalid time"))
    _       <- sql"INSERT INTO other_table (id, timestamp) VALUES (42, $newTime)".update.run.transact(tx)
  } yield newTime
```

What I'm trying to implement is to rollback the first transaction if the response from the other service is `false`. What would be the best way to implement rollbacks in this case?

**Comment by jatcwang** [comment]
Whenever you run `transact` you are committing the transaction so with your current code you cannot roll back a transaction.

What you want to do is to run all your statements within one ConnectionIO, which means all statements are executed in one transaction (by default).

```
import doobie.hi.connection
import doobie.ConnectionIO
import cats.ApplicativeError

def genNewTime(tx: Transactor[IO]): IO[ZonedDateTime] =
  (for {
    newTime <- sql"UPDATE main_table SET new_time = NOW() WHERE id = 42".update
      .withUniqueGeneratedKeys[ZonedDateTime]("new_time")
    _       <- ApplicativeError[ConnectionIO, Throwable].raiseUnless(isTimeValid(newTime))(new Throwable("invalid time"))
    _       <- sql"INSERT INTO other_table (id, timestamp) VALUES (42, $newTime)".update.run
  } yield newTime).transact(tx)
```

Note that I made `isTimeValid` a pure function instead of returning IO[Boolean]. If you really need to run an IO in CoonectionIO chain then look into using WeakAsync https://stackoverflow.com/a/71257623

**Comment by kyri-petrou** [comment]
Thanks a lot for the info! Unfortunately the toy `isTimeValid` function can't be made pure since it's actually a call to another external service. However WeakAsync seems to do the job. Thanks for sharing that, much appreciated!
