### ISSUE TITLE
Allowing writing Option.None as DEFAULT instead of NULL

### ISSUE THREAD

**Issue by keisar** [tpolecat/doobie#1796]
I have a use case where I need to write None values as default values instead of null using postgres' "default" keyword, the end result of my insert statement should look something like:
`INSERT INTO table(col1, col2, col3) VALUES (DEFAULT, "hello", world")`

I tried implementing a new type called `OptionDefault` with a `Put` but it seemed to me Put is lacking a way to write anything else other than the actual value or "NULL", is this correct? 

If you believe this is feasible and makes sense, I'll be happy to make the modifications to enable this functionality, but I'll need a little guidance on how is best to approach it.
I thought maybe changing `unsafeSetNonNullable` and `unsafeUpdateNonNullable` to include a boolean for using the default keyword if null is provided (or maybe creating `unsafeSetWithDefault`)

**Comment by jatcwang** [comment]
From a quick look around, I don't think PostgreSQL itself allows this. i.e. this won't work: `INSERT INTO table(col1, col2, col3) SELECT COALESCE(?, DEFAULT), ?, ?` because DEFAULT can only be used in VALUE clause but then we can't use COALESCE.

So all the solutions people of providing involves dynamically generating a different SQL depending on whether your column values are present. And it'd be the same in Scala too: 

```
val col1ValueOpt: Option[String] = // ...

col1ValueOpt match {
  case Some(col1) => sql"INSERT INTO table(col1, col2, col3) VALUES (${col1}, 'hello', world')"
  case None => sql"INSERT INTO table(col1, col2, col3) VALUES (DEFAULT, 'hello', 'world')"
}
```

**Comment by keisar** [comment]
Hey @jatcwang, thanks for the quick reply!
I probably didn't explain myself well enough, otherwise I'm not sure why we need COALESCE here?

I have a simple case class with a three fields:
1. val col1: Option[String] = None
2. val col2: String = "Hello"
3. val col3: String = "World"

Using Doobie now I get this insert statement: `INSERT INTO table(col1, col2, col3) VALUES (NULL, "Hello", "World")`
What I need is: `INSERT INTO table(col1, col2, col3) VALUES (DEFAULT, "Hello", "World")`

I hope it is clearer now, if I misunderstood please let me know what I missed 😅

**Comment by jatcwang** [comment]
@keisar Yeah I was trying to low-key explain that the SQL the database see is NOT `INSERT INTO table(col1, col2, col3) VALUES (NULL, "Hello", "World")` 😄 . It's actually `INSERT INTO table(col1, col2, col3) VALUES (?, ?, ?)` with the parameters of `[null, "Hello", "World"]` passed separately. This is how databases avoid SQL injection attacks (amongst other things)

Doobie uses JDBC under the hood, so https://www.tutorialspoint.com/what-is-preparedstatement-in-jdbc might help you understand what goes on at the JDBC level.
(Also btw this is not a JDBC limitation. This is how all database work when it comes to prepared statements & parameters)

In order to convince PostgreSQL to use the default value you need the SQL `INSERT INTO table(col1, col2, col3) VALUES (DEFAULT, ?, ?)`, but that's impossible to do from just changing the value of parameters (col1) will never allow you to change the SQL Postgres sees.

Hope that explains why you need to create a different SQL based on value of col1 (the snippet in my last comment)

**Comment by keisar** [comment]
That's perfectly clear @jatcwang, thanks!
very unfortunate as it means we can't use bulk inserts for different types where one type needs to use the default value from the DB as it means we need to change the number of columns in the insert statement.
For now we'll use default values in our code.

Appreciate you taking the time to explain it :D
