### ISSUE TITLE
Fragments.whereAndOpt in 1.0.0 RC3 and RC4 trouble

### ISSUE THREAD

**Issue by DenisNovac** [tpolecat/doobie#1909]
I have following query:

```scala
    sql"""SELECT TOP($l) * FROM journal ${Fragments.whereAndOpt(
        userSql,
        fromSql,
        toSql
      )} ORDER BY ts $orderSql"""
```

In logger i see it constructs SQL `SELECT TOP(?) * FROM journal WHERE ts >= ?AND ts <= ? ORDER BY ts ASC`. There is no space before "AND" so i get error `Must declare the scalar variable "@P1AND"`. Same query works fine in `1.0.0-RC2`.

**Comment by jatcwang** [comment]
Ah sorry that slipped through because we mostly assume the use of `fr` (which adds a space at the end of each fragment) https://tpolecat.github.io/doobie/docs/08-Fragments.html#whitespace-handling

But seems like `sql` interpolator is popular too (equivalent to fr0) so I think we should ensure it works for it
