### ISSUE TITLE
Add Composability with other Free Algebras

### ISSUE THREAD

**Issue by beefyhalo** [tpolecat/doobie#282]
I'd like to compose doobie programs with other free algebras "data a la carte" style (using `scalaz.Inject`).

**Comment by peterneyens** [comment]
@tpolecat I looked into your [suggestion](https://gitter.im/tpolecat/doobie?at=57f173f8d38f186520bbbe1c) to @raulraja of using `transK` to get transactions when combining Free algebras where some of them can be interpreted to `ConnectionIO`.

I created a [proof of concept](https://github.com/peterneyens/freedoobie) (using the _doobie-core-cats_ snapshot). In short there are 2 interpreters for 2 ADTS, one to `IOLite`, one to `ConnectionIO` which are both lifted to return a `Kleisli[IOLite, Connection, ?]`.

To get transactions for `Kleisli[M, Connection, ?]`, I essentially need to recreate something like a `Transactor` but for `Kleisli[M, Connection, ?]` (which I dubbed `ConIOK[M, ?]` in my example). It would be nice if I could reuse the `connect` method from `Transactor` to get a `M[Connection]`, but is protected (in order to not leak connections I suppose). In my example I created a `Transactor` subclass which exposes the `connect` method as `connectHack` as a hacky workaround.

I am interested in your opinion about this technique.

Like you mentioned, Interleaving of effects can be difficult / dangerous ("how to call back the missiles in case of a rollback"): I could require a type class instance of something like `ReExecutable[F[_]]` / `CanBeInterleaved[F[_]]` before lifting an `F ~> M` interpreter to `F ~> ConIOK[M, ?]` so you don't end up shooting yourself in the foot.

**Comment by wedens** [comment]
it is solved by new transactor/interpreters design, isn't it?

**Comment by tpolecat** [comment]
Somehow I missed this. There is a [coproduct example](https://github.com/tpolecat/doobie/blob/series/0.4.x/yax/example/src/main/scala/example/Coproduct.scala) that addresses this question I think.

**Comment by beefyhalo** [comment]
Nice! Marking as closed. FWIW, I forgot about this "issue"... and after gaining some experience, I don't think I needed this all along.
