### ISSUE TITLE
What setup is necessary to run the doobie tests?

### ISSUE THREAD

**Issue by nuttycom** [tpolecat/doobie#306]
Would it be possible to add a bit to the README to indicate what setup is necessary to run the test suite(s)? I'm working on upgrading to scalaz 7.2.4 and getting rid of some deprecation warnings, and I'd like to be able to run the whole suite.

**Comment by tpolecat** [comment]
Hey Kris, that's a good idea. If you look at the `.travis.yml` you'll see what you need ... the Postgres tests and tut doc need a test database (and default `postgres` user with no password), otherwise everything you need should be on the classpath. Let me know if you run into trouble.

Also feel free to open a WIP PR and let Travis deal with it.

Leaving open … need to add a `CONTRIBUTORS.md` file now that there are, uh, contributors.

**Comment by tpolecat** [comment]
Closing; opened #348
