### ISSUE TITLE
Is there a way to get typed results for arbitrary SQL queries?

### ISSUE THREAD

**Issue by ayersb** [tpolecat/doobie#371]
My team has a somewhat odd use case for Doobie, and we’re wondering if there is a way to use metadata to apply type information over untyped objects obtained from a JDBC ResultSet at runtime? My team’s using Doobie as part of the back end for a cloud based SQL workbench like application, so we need to be able to handle arbitrary SQL queries submitted by users. We’ve used the low level API to submit our arbitrary queries and get results back as Java Objects, and we can get meta data for the queries using the high level API. I'm not sure if it's possible without runtime code generation, but is there a way we could use take the "Any" type collections we get from JDBC and use the meta data object from the doobie high level API to create a fully typed Scala collection?
e.g. If use user submit some query "SELECT id, name FROM peoples", and is there any way we could use our

`val jdbcResultRows: Vector[Vector[Any]] = ...`
and
`val metaData : List[ColumnMeta] =` 
`List(ColumnMeta(Integer,INTEGER,NoNulls,CODE),ColumnMeta(VarChar,VARCHAR,NoNulls,NAME))`

to get something like
    `val typedResults: Vector[(Int,String)] = magicFunction(jdbcResultRows, metaData)`
where presumably `(Int, String)` would be an HList?

**Comment by tpolecat** [comment]
I'm curious, where would you write the line of code

```scala
val typedResults: Vector[(Int,String)] 
```
because If you know at compile-time that you're expecting rows of `(Int, String)` then you could just use the existing machinery. So I think possibly this isn't really what you need to do?

In general you *can* take the information you have and use it to render a table for instance, since you can say ok the first thing (which is an `Any`) has a JDBC type of `INTEGER` so I know it's going to be an `Int` or Java `Integer` (depending on how you pulled the value out) and I can use that information locally to render it in a reasonable way. So you can use the metadata to refine the type but you won't know which code path it will take until runtime.

Maybe you can say a bit more about how what you're trying to do?

**Comment by tpolecat** [comment]
Closing this. Feel free to re-open if you want to continue discussing.
