### ISSUE TITLE
Meta[Char] instance missing

### ISSUE THREAD

**Issue by japgolly** [tpolecat/doobie#396]
Is this intentional or an oversight?

**Comment by tpolecat** [comment]
There is no JDBC mapping for Java `char`. You could define a mapping from SQL `CHAR(1)` or a vendor-specific unsigned short but there's nothing built in. What is the underlying column type you wish to map?

**Comment by japgolly** [comment]
The underlying column type I have is `"char"` in Postgres (those quotes are needed btw).

If there's a built-in mapping for `varchar↔String`, so I was thinking there should be one for `char↔char` too so as it's a subset on both sides.

**Comment by tpolecat** [comment]
Ok, the `"char"` type in Postgres is a single byte so it's not really a `Char` … you could define a mapping for a custom data type, or a partial mapping that only works for chars < 256. The built-in `Byte` mapping doesn't work because the driver expects character data. The driver treats it like `CHAR(1)` but values outside the 1-byte range get smashed to 0xFFFD when you read them back. Not sure how they end up on the db side.

If you're sure the chars you're writing are all ASCII (for instance) you can get away with this mapping.

```scala
implicit val CharMeta = Meta[String].xmap[Char](
  s => if (s != null) s.head else '?', // dummy value will never be observed
  c => c.toString
)
```

**Comment by japgolly** [comment]
I tried using `Byte` ran into a driver runtime exception so I ended up just going via `String` like your example. Oh well, thanks anyway and thank you for the explanation and advice. I'm good to close this issue if you are.

**Comment by tpolecat** [comment]
Cool, feel free to reopen if you run into trouble.

**Comment by sentenza** [comment]
My solution was to introduce this implicit:

```scala
implicit val CharMeta =
      Meta[String].timap[Char]((s: String) => s.toCharArray()(0))((c: Char) => c.toString)
```
