### ISSUE TITLE
.attempt is not working with *-cats variants

### ISSUE THREAD

**Issue by ihji** [tpolecat/doobie#447]
`.attempt` is not working without `import fs2.interop.cats._` when you use 0.4 version of *-cats variants. However, it works without `import` in 0.3 cats milestone. It would be nice if we have a note about this in FAQ.

**Comment by guersam** [comment]
doobie had its own `Catchable` for cats until [dropped in favor of `fs2.util.Catchable`](https://github.com/tpolecat/doobie/commit/849142f669c93d6824a93f0fc6e023ffe0152c13). I usually add `import fs2.interop.cats._` to every file using doobie but it gets annoying sometimes.

Just random thought; what if we make `doobie.imports` extends `fs2.interop.cats.Instances`? But then 1) we might suffer from ambiguous implicit error due to the orphan instances, and 2) there might be some corner cases the reverse instances (e.g. `cats.Monad` -> `fs2.util.Monad`) are needed causing unwanted divergence.

Maybe https://github.com/milessabin/export-hook will solve this issue, but I'm afraid of adding new dependency both to fs2-cats and doobie.

**Comment by tpolecat** [comment]
Yeah I think for now we can tell people they just have to import the interop layer. I'd like to factor out streams and fs2 which will require a third library to provide `Capture/Suspendable` and `Catchable` … I want to see if I can get Michael on board at NEScala.

**Comment by tpolecat** [comment]
duplicated by #477
