### ISSUE TITLE
Update0.updateMany swallows error flags in the returned int[] from Statement.executeBatch

### ISSUE THREAD

**Issue by mfelsche** [tpolecat/doobie#706]
The docs for [Statement.executeBatch](https://docs.oracle.com/javase/8/docs/api/java/sql/Statement.html#executeBatch--) from the JDBC Api explicitly state that possible values are: >=0 which is the update count, `SUCCESS_NO_INFO (= -2)` or `EXECUTE_FAILED (=-3)`. The current `updateMany` implementation sums the int array and thus treating those values as update counts, which leads to incorrect results. The returned int could even become negative. 

The sum is applied here: https://github.com/tpolecat/doobie/blob/series/0.5.x/modules/core/src/main/scala/doobie/hi/preparedstatement.scala#L72

To me it would make sense to return the int array as list and not sum it up in the first place. Another improvement (which i wouldn't favor) would be to filter out negative values and treat them as rows not being updated, which would not convey the whole information, but at least a little more:

```scala
  def addBatchesAndExecute[F[_]: Foldable, A: Composite](fa: F[A]): PreparedStatementIO[Int] =
    fa.toList.foldRight(executeBatch)((a, b) => set(a) *> addBatch *> b).filter(_ > 0).map(_.sum)
```

**Comment by tpolecat** [comment]
Oops, good catch. Thanks.

**Comment by tpolecat** [comment]
I'm unable to come up with a test case that returns a negative number rather than throwing an exception. Do you have an example?

**Comment by tpolecat** [comment]
Cool I'll try that one.

**Comment by tpolecat** [comment]
Hm yeah I'm getting a `BatchUpdateException` from that as well.

**Comment by Daenyth** [comment]
Is this still a problem?

**Comment by ayoub-benali** [comment]
yes I guess because there isn't yet a way to get the error messages if some rows aren't inserted.

**Comment by nigredo-tori** [comment]
I've came here from the `Update.updateMany` scaladoc. It has a sentence that reads like this:

> Note that failed updates are not reported (see https://github.com/tpolecat/doobie/issues/706).

This sounds terrifying! It also sounds suspicious - it should use Java APIs, and what Java API would miss an opportunity to throw an exception? :smile: So I did some digging - and, apparently, `executeBatch` shouldn't **return** any `EXECUTE_FAILED` values. Consider this fragment of the [`executeBranch` Javadoc](https://docs.oracle.com/en/java/javase/11/docs/api/java.sql/java/sql/Statement.html#executeBatch()):

> The elements in the array returned by the method executeBatch may be one of the following:
> 1. A number greater than or equal to zero -- indicates that the command was processed successfully and is an update count giving the number of rows in the database that were affected by the command's execution
> 2. A value of SUCCESS_NO_INFO -- indicates that the command was processed successfully but that the number of rows affected is unknown
>   
>     **If one of the commands in a batch update fails to execute properly, this method throws a BatchUpdateException**, and a JDBC driver may or may not continue to process the remaining commands in the batch. However, the driver's behavior must be consistent with a particular DBMS, either always continuing to process commands or never continuing to process commands. If the driver continues processing after a failure, the array returned by the method BatchUpdateException.getUpdateCounts will contain as many elements as there are commands in the batch, and **at least one of the elements will be the following**:
>
> 3. A value of EXECUTE_FAILED -- indicates that the command failed to execute successfully and occurs only if a driver continues to process commands after a command fails

It is my understanding that this was misinterpreted due to broken formatting - the paragraph with highlighted text is not a part of item 2, and item 3 should be a separate (one-element) list.

Could we please amend [these parts](https://github.com/tpolecat/doobie/search?q=%22updates+are+not+reported%22) of the scaladoc?
