### ISSUE TITLE
`Meta` for `List[String]` no longer available in 0.6.0-M2

### ISSUE THREAD

**Issue by jurisk** [tpolecat/doobie#770]
Assume I have value class `Something` wrapping String which I want to store in `TEXT[]` field.

In 0.5.x I could do:

```scala
case class Something(value: String) extends AnyVal

implicit private val SomethingListMeta: Meta[List[Something]] = Meta[List[String]].xmap (
    _.map(Something),
    _.map(_.value)
  )

// CREATE TABLE some_table (id INT PRIMARY KEY, somethings TEXT[])
private def insertData(id: Int, somethings: List[Something) = {
   sql"INSERT INTO some_table (id, somethings) VALUES (${id}, ${somethings}".update.run
}
```

Doing the same in 0.6.0-M2 leads to: `could not find implicit value for parameter ev: doobie.util.Meta[List[String]]`.

**Comment by tpolecat** [comment]
`Meta`-to-`Meta` derivation is discouraged because it can lead to ambiguities, so instead of deriving `Meta[List[...]]` from `Meta[Array[...]]]` we derive a pair `Get[List[...]]` and `Put[List[...]]`. So you have two choices:

- you can use `Meta[Array[String]]` as the basis; or
- you can use `Get[List[String]]` and `Put[List[String]]` and define both instances.

**Comment by jurisk** [comment]
Thanks, the solution you proposed worked.
