### ISSUE TITLE
Minimal example with fromDriverManager, H2, IOChecker

### ISSUE THREAD

**Issue by mcanlas** [tpolecat/doobie#792]
When I run the following, it seems that the `foo` table isn't available. Maybe it's my misunderstanding of the execution model. Is there something amiss?

Also, just generally wondering what the narrative for `IOChecker` should be if creating a `Transactor` is normally suspended in a side effect but the signature for `IOChecker` lacks one.

```scala
class FailingSpec extends FreeSpec with IOChecker {
  def transactor: Transactor[IO] = {
    implicit val cs: cats.effect.ContextShift[IO] =
      IO.contextShift(scala.concurrent.ExecutionContext.global)

    val createSql =
      sql"""CREATE TABLE foo (a int)"""

    val tx =
      Transactor
        .fromDriverManager[IO]("org.h2.Driver", "jdbc:h2:mem:")

    createSql
      .update
      .run
      .transact(tx)
      .unsafeRunSync()

    tx
  }

  "type safe queries in h2" - {
    "select one" in {
      check(sql"""select * from foo""".query[Int])
    }
  }
}
```

**Comment by tpolecat** [comment]
By default an in-memory H2 database only lasts for a single connection, then next time you connect you get a fresh empty one. You need to add `DB_CLOSE_DELAY=-1` to prevent it from timing out, and should probably name the database as well: `"jdbc:h2:mem:MyDatabase;DB_CLOSE_DELAY=-1"`

Note that every time you call `transactor` you get will a new one. This probably isn't what you want. Make this a `val` or `lazy val`.  I would put the DDL in its own `ConnectionIO` program and compose it with tests that need it, rather than side-effecting. You can use `CREATE TABLE IF NOT EXISTS` to make it ok to run more than once. Or, you can add to the `before` action on your transactor so it happens automatically each time.

Follow up here or on the gitter channel if you need more help.

**Comment by mcanlas** [comment]
Ahh, I think I get it now regarding H2. It must have worked in my other (unposted) code because a connection was being held open.

Regarding composition, where would it go? Would you just consume the `tx` each time? Otherwise I'm not sure I understand, type-wise.

```scala
"some test" in runCreateIdempotent(tx) {
  "select one" in {
    check(sql"""select * from foo""".query[Int])
  }
}
```

I.e. the side effect is in the scope of the test but not anywhere near the check or the SQL?
