### ISSUE TITLE
publish for Scala 2.13.0-RC1?

### ISSUE THREAD

**Issue by SethTisue** [tpolecat/doobie#898]
are there any of your dependencies we need to go chasing after...?

**Comment by ChristopherDavenport** [comment]
I think this would be after a stable 0.7.0 with the old dependency set. 

The only one I'm aware still missing for this is fs2.

**Comment by tpolecat** [comment]
I don't have strong feelings about 0.7.0 … I will ship it with whatever version of 2.13 works at the time.

**Comment by ChristopherDavenport** [comment]
The RC only has releases against new major versions of your upstreams, and I would very much like to have a stable position across the old versions of them first.

Since the cancellation issue makes 0.6 unsafe with http4s servers automatic cancellation properaties.

**Comment by tpolecat** [comment]
Can you say that again with more words? I don't think I understand your concern.

**Comment by ChristopherDavenport** [comment]
My concern is that we won't get a stable 0.7.x release against fs2/cats-effect/cats 1.x versions. 

I would very much like a stable on those versions. 

But all of those libraries are releasing new versions in order to release for RC1. So I believe that would mean for doobie to support a 2.13.0-RC1 for those would require a 0.8.x here very shortly after a stable 0.7.x

**Comment by SethTisue** [comment]
@tpolecat should this still be open?

**Comment by tpolecat** [comment]
Nope, thanks.
